from .animal import Animal
from .copperhead import Copperhead
from .coralsnake import Coralsnake
from .coy import Coy
from .donkey import Donkey
from .duck import Duck
from .frog import Frog
from .goat import Goat
from .goldfish import Goldfish
from .goose import Goose
from .horse import Horse
from .llama import Llama
from .moccassin import Moccassin
from .python import Python
from .ratsnake import Ratsnake
from .sheep import Sheep